version: '3'
services:
  playground:                 
    container_name: 'QiiCast-Frontend'  
    hostname: 'python'        

    build: .                 
    shm_size: '8gb'
    restart: always          
    working_dir: '/app' 
    tty: true            
    volumes:             
      - type: bind       
        source: ../  
        target: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]